[project]
name = "bq-samples"
version = "0.1.0"
description = "BigQuery samples"
authors = [
    {name = "Flyaps",email = "info@flyaps.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-bigquery (>=3.41.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
